<?php

namespace app\commons ;

use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii2mod\rbac\filters\AccessControl;

class BaseController extends Controller
{

        public function behaviors()
        {
            $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
            $myBehavior = [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
                'access' => [
                    'class' => AccessControl::className(),
                    'rules' => [
                        [
                            'actions' => ['index', 'view' ,'create' ,'update','delete'],
                            'allow' => true,
                            'roles' => ['@'],
                        ],
                    ],
                ],
            ];

            return array_merge($behaviors,$myBehavior) ;
        }
}