<?php
/**
 * Created by PhpStorm.
 * User: amir changizi
 * Date: 12/6/2017
 * Time: 7:30 PM
 */

namespace frontend\widgets\html;


use yii\base\Widget;

class MasaHtmlWidget extends Widget
{

    public $section = 'Home' ;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $model = \common\modules\catalog\models\Html::find()->where(['possition'=>$this->section])->all();

        return $this->render('html',compact('model'));
    }
}