<?php

/**
 * Created by PhpStorm.
 * User: shabake
 * Date: 11/19/2017
 * Time: 10:53 PM
 */

namespace common\modules\shopconfig\Behaviors;


use yii\base\Behavior;
use yii\behaviors\AttributeBehavior;
use yii\db\ActiveRecord;

/**
 * Class LanguageBehavior
 *
 * @property ActiveRecord $owner
 *
 * @package common\modules\shopconfig\Behaviors
 */

class LanguageBehavior extends AttributeBehavior
{

    public function events ()
    {
        return [
            ActiveRecord :: EVENT_AFTER_INSERT => 'AfterInsert',
            ActiveRecord :: EVENT_BEFORE_UPDATE => 'BeforeUpdate' ,
            ActiveRecord :: EVENT_AFTER_DELETE => 'afterDelete'
        //Controller :: EVENT_BEFORE_ACTION => 'BeforeAction' - is used for reports
     ];
 }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        print_r($this->owner->attributes());

        exit ;
    }



}