<?php
/**
 * User: amir changizi
 * Date: 10/13/2017
 * Time: 11:17 AM
 */

namespace common\modules\customermanagement\actions;


use common\modules\customermanagement\models\Customers;
use Yii ;
use yii\base\Action ;
use yii\web\NotFoundHttpException;
use common\modules\customermanagement\models\LoginForm;


class LvsRAction extends Action
{

    const EVENT_AFTER_LOGIN = 'afterLogin' ;

    const EVENT_BEFORE_LOGIN = 'beforeLogin' ;

    public $active_partial = false ;

    public function init()
    {
        //$this->on(self::EVENT_AFTER_LOGIN, ['app\modules\usermanagement\events\UserEvent', 'afterLogin']);
        return parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        try
        {

            if (!Yii::$app->user->isGuest) {
                return $this->controller->goHome();
            }

            $model = new LoginForm();
            $signupModel = new Customers() ;
            if ($model->load(Yii::$app->request->post()) && $model->login()) {

                return $this->controller->goBack();
            }
            if ($signupModel->load(Yii::$app->request->post()) && $signupModel->save() ) {
                return $this->controller->redirect(['site/index']) ;
            }
            if($this->active_partial)
                return $this->controller->renderPartial('login', [
                    'model' => $model,
                    'signupModel' => $signupModel,
                ]);


            return $this->controller->render('login', [
                'model' => $model,
                'signupModel' => $signupModel,
            ]);
        }
        catch (\Exception $e)
        {
            throw new NotFoundHttpException($e->getCode(),$e->getMessage()) ;
        }
    }



}