<?php

namespace frontend\commons ;

use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\filters\AccessControl ;

class BaseController extends Controller
{

        public function behaviors()
        {
            $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
            $myBehavior = [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
                /*'access' => [
                    'class' => AccessControl::className(),
                    'rules' => [
                        [
                            'actions' => ['index', 'view' ,'create' ,'update','delete'],
                            'allow' => true,
                            'roles' => ['@'],
                        ],
                    ],
                ],*/
            ];

            return array_merge($behaviors,$myBehavior) ;
        }

        public function init()
        {
            $cookies = Yii::$app->request->cookies;
            if (isset($cookies['language']))
            {
                Yii::$app->language = $cookies['language']->value  ;
            }

            return parent::init(); // TODO: Change the autogenerated stub
        }
}