<?php
namespace app\modules\usermanagement\commons;

use Yii ;
use app\commons\BaseController;

class BaseUserController extends BaseController
{
    protected $userModule ;

    public function init()
    {
        $this->userModule =  Yii::$app->getModule('UserManagement');
        return parent::init(); // TODO: Change the autogenerated stub
    }

}